version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=accessBase.settings
      - DJANGO_DEBUG=True
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  # Ajoutez d'autres services si nécessaire, par exemple, pour une base de données
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: your_database
  #     POSTGRES_USER: your_user
  #     POSTGRES_PASSWORD: your_password