# Generated by Django 4.1.7 on 2023-11-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessVisionBack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='alerte',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='french_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
