# Generated by Django 4.1.7 on 2023-12-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessVisionBack', '0002_element_alerte_element_french_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('tracking', models.TextField()),
            ],
        ),
    ]
